version: '3.8'

services:
  db:
    image: postgres:15
    container_name: eventmaster_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=eventmaster_db
      - POSTGRES_USER=gana_admin
      - POSTGRES_PASSWORD=votre_mot_de_passe
    ports:
      - "5433:5432"  # On mappe le port 5433 de ton PC vers le 5432 du conteneur (évite les conflits)

  web:
    build: .
    container_name: eventmaster_web_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=eventmaster_db
      - DATABASE_USER=gana_admin
      - DATABASE_PASSWORD=votre_mot_de_passe
      - DATABASE_HOST=db  # Très important : on utilise le nom du service 'db' comme hôte
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: